apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: kubechat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: kubechat/chat-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50053
        env:
        - name: PORT
          value: "50053"
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: MESSAGE_STORE_URL
          value: "message-store-service:50054"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: kubechat
spec:
  selector:
    app: chat-service
  ports:
  - port: 50053
    targetPort: 50053
  type: ClusterIP