apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  namespace: kubechat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
    spec:
      containers:
      - name: presence-service
        image: kubechat/presence-service:latest
        ports:
        - containerPort: 50052
        env:
        - name: PORT
          value: "50052"
        - name: NATS_URL
          value: "nats://nats:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: presence-service
  namespace: kubechat
spec:
  selector:
    app: presence-service
  ports:
  - port: 50052
    targetPort: 50052
  type: ClusterIP