apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: kubechat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: users-service
        image: kubechat/users-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: kubechat
spec:
  selector:
    app: users-service
  ports:
  - port: 50051
    targetPort: 50051
  type: ClusterIP