// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/messagestore.proto

package messagestore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMessageRequest) Reset() {
	*x = StoreMessageRequest{}
	mi := &file_proto_messagestore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessageRequest) ProtoMessage() {}

func (x *StoreMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessageRequest.ProtoReflect.Descriptor instead.
func (*StoreMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{0}
}

func (x *StoreMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StoreMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *StoreMessageRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *StoreMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreMessageRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StoreMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMessageResponse) Reset() {
	*x = StoreMessageResponse{}
	mi := &file_proto_messagestore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessageResponse) ProtoMessage() {}

func (x *StoreMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessageResponse.ProtoReflect.Descriptor instead.
func (*StoreMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{1}
}

func (x *StoreMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetMessageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       string                 `protobuf:"bytes,1,opt,name=user_id1,json=userId1,proto3" json:"user_id1,omitempty"`
	UserId2       string                 `protobuf:"bytes,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageHistoryRequest) Reset() {
	*x = GetMessageHistoryRequest{}
	mi := &file_proto_messagestore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageHistoryRequest) ProtoMessage() {}

func (x *GetMessageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetMessageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageHistoryRequest) GetUserId1() string {
	if x != nil {
		return x.UserId1
	}
	return ""
}

func (x *GetMessageHistoryRequest) GetUserId2() string {
	if x != nil {
		return x.UserId2
	}
	return ""
}

func (x *GetMessageHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessageHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetMessageHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*StoredMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageHistoryResponse) Reset() {
	*x = GetMessageHistoryResponse{}
	mi := &file_proto_messagestore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageHistoryResponse) ProtoMessage() {}

func (x *GetMessageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetMessageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageHistoryResponse) GetMessages() []*StoredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_messagestore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_proto_messagestore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StoredMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   string                 `protobuf:"bytes,3,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	mi := &file_proto_messagestore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messagestore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_proto_messagestore_proto_rawDescGZIP(), []int{6}
}

func (x *StoredMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *StoredMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *StoredMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *StoredMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoredMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StoredMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_messagestore_proto protoreflect.FileDescriptor

const file_proto_messagestore_proto_rawDesc = "" +
	"\n" +
	"\x18proto/messagestore.proto\x12\fmessagestore\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x01\n" +
	"\x13StoreMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"F\n" +
	"\x14StoreMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"~\n" +
	"\x18GetMessageHistoryRequest\x12\x19\n" +
	"\buser_id1\x18\x01 \x01(\tR\auserId1\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\tR\auserId2\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"T\n" +
	"\x19GetMessageHistoryResponse\x127\n" +
	"\bmessages\x18\x01 \x03(\v2\x1b.messagestore.StoredMessageR\bmessages\"N\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x15DeleteMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xfd\x01\n" +
	"\rStoredMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x03 \x01(\tR\vrecipientId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xac\x02\n" +
	"\x13MessageStoreService\x12U\n" +
	"\fStoreMessage\x12!.messagestore.StoreMessageRequest\x1a\".messagestore.StoreMessageResponse\x12d\n" +
	"\x11GetMessageHistory\x12&.messagestore.GetMessageHistoryRequest\x1a'.messagestore.GetMessageHistoryResponse\x12X\n" +
	"\rDeleteMessage\x12\".messagestore.DeleteMessageRequest\x1a#.messagestore.DeleteMessageResponseB\x16Z\x14./proto/messagestoreb\x06proto3"

var (
	file_proto_messagestore_proto_rawDescOnce sync.Once
	file_proto_messagestore_proto_rawDescData []byte
)

func file_proto_messagestore_proto_rawDescGZIP() []byte {
	file_proto_messagestore_proto_rawDescOnce.Do(func() {
		file_proto_messagestore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messagestore_proto_rawDesc), len(file_proto_messagestore_proto_rawDesc)))
	})
	return file_proto_messagestore_proto_rawDescData
}

var file_proto_messagestore_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_messagestore_proto_goTypes = []any{
	(*StoreMessageRequest)(nil),       // 0: messagestore.StoreMessageRequest
	(*StoreMessageResponse)(nil),      // 1: messagestore.StoreMessageResponse
	(*GetMessageHistoryRequest)(nil),  // 2: messagestore.GetMessageHistoryRequest
	(*GetMessageHistoryResponse)(nil), // 3: messagestore.GetMessageHistoryResponse
	(*DeleteMessageRequest)(nil),      // 4: messagestore.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),     // 5: messagestore.DeleteMessageResponse
	(*StoredMessage)(nil),             // 6: messagestore.StoredMessage
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_proto_messagestore_proto_depIdxs = []int32{
	7, // 0: messagestore.StoreMessageRequest.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: messagestore.GetMessageHistoryResponse.messages:type_name -> messagestore.StoredMessage
	7, // 2: messagestore.StoredMessage.timestamp:type_name -> google.protobuf.Timestamp
	7, // 3: messagestore.StoredMessage.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: messagestore.MessageStoreService.StoreMessage:input_type -> messagestore.StoreMessageRequest
	2, // 5: messagestore.MessageStoreService.GetMessageHistory:input_type -> messagestore.GetMessageHistoryRequest
	4, // 6: messagestore.MessageStoreService.DeleteMessage:input_type -> messagestore.DeleteMessageRequest
	1, // 7: messagestore.MessageStoreService.StoreMessage:output_type -> messagestore.StoreMessageResponse
	3, // 8: messagestore.MessageStoreService.GetMessageHistory:output_type -> messagestore.GetMessageHistoryResponse
	5, // 9: messagestore.MessageStoreService.DeleteMessage:output_type -> messagestore.DeleteMessageResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_messagestore_proto_init() }
func file_proto_messagestore_proto_init() {
	if File_proto_messagestore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messagestore_proto_rawDesc), len(file_proto_messagestore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messagestore_proto_goTypes,
		DependencyIndexes: file_proto_messagestore_proto_depIdxs,
		MessageInfos:      file_proto_messagestore_proto_msgTypes,
	}.Build()
	File_proto_messagestore_proto = out.File
	file_proto_messagestore_proto_goTypes = nil
	file_proto_messagestore_proto_depIdxs = nil
}
